<?php

namespace Tests\Unit\Ingest;

use Illuminate\Support\Str;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * `docs/design/FLEET-STATE.md § 6.5`, condition 1 (card#9398): `App\Ingest\BatchWriter` is the only
 * code that writes rows into `events`.
 *
 * The fold's cursor reads `events` by `id > cursor` and never looks back. That is safe only because
 * every transaction that allocates an `events` id holds the seat's `seat_state` row lock from its
 * first statement to its commit, which `BatchWriter::write()` does. A second inserter anywhere else
 * does not take that lock, so its ids can commit below one the fold has already read past, and those
 * events are never folded and nothing reports it. That is the defect card#9398 fixed. Before this
 * test, the only check was a grep written into comments, `table('events')->insert`, which did not
 * match the real call (`insertOrIgnore`) and which nothing ran.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────
 * WHAT COUNTS AS A WRITE, AND WHY.
 *
 *   INSERT-shaped, the ones condition 1 is about because they allocate ids: the query builder's
 *   `insert`, `insertOrIgnore`, `insertGetId`, `insertUsing`, `insertOrIgnoreUsing`, `upsert` and
 *   `updateOrInsert` on `table('events')`; raw SQL `INSERT` or `REPLACE` into `events`; and an
 *   Eloquent model on `events`, whether its `$table` says so or its class name infers it.
 *
 *   UPDATE-shaped, which are included: the builder's `update`, `increment`, `decrement` and their
 *   `…Each` forms, and raw `UPDATE events`. An UPDATE allocates no id, but no code in this tree
 *   updates `events` (this test is what measures that), rows are stored as received and never
 *   rewritten (D1 decision 19), and an UPDATE that moves a row's `id` or `seat_ref` strands it behind
 *   a cursor exactly as a late insert does. A future UPDATE that is genuinely harmless is a design
 *   change to argue on its own card, with this file edited in the same change.
 *
 *   DELETEs are out of scope. `App\Sweep\Purge` deletes expired `events` rows by design, and removing
 *   a row can never put one below the cursor. Reads are out of scope too.
 *
 *   `table('events')` means exactly that table. `events_archive` or any other name that only starts
 *   with `events` is a different table and is not matched.
 *
 * WHAT THE SCAN CANNOT SEE, stated so nobody reads green as more than it is. A table name the source
 * does not spell as a literal (`DB::table($table)`, `sprintf('INSERT INTO %s', …)`, a string built by
 * concatenation); a builder held in a property, or in a variable passed to another method or file
 * before the write; SQL inside a Blade `@php` block. In today's tree, `Purge` is the computed-name builder and it
 * only counts and deletes, and `App\Ingest\Counters` is the computed-name raw INSERT and it writes the
 * counter tables its callers name.
 *
 * THE POPULATION is re-derived on every run: every `.php` file under `server/`, minus the directories
 * in `NOT_APPLICATION_CODE`, each with the reason it is out. That is wider than `server/app` on
 * purpose: a data migration or a route closure that inserts into `events` is a second inserter too.
 *
 * ⭐ THE CONTROLS. `test_the_scanner_finds_each_write_shape` feeds the scanner a planted writer of
 * every shape above and asserts it is reported, and `test_the_scanner_ignores_what_is_not_a_write`
 * feeds it the near-misses. `test_the_scanner_finds_the_real_inserter` asserts it finds
 * `BatchWriter`'s own insert, so a scanner that has stopped matching the call the tree actually makes
 * (the way the old grep never matched it) goes red instead of passing over an empty result.
 */
class EventsHaveOneWriterTest extends TestCase
{
    /** The one file allowed to write to `events`, relative to `server/`. */
    private const THE_WRITER = 'app/Ingest/BatchWriter.php';

    /**
     * Directories under `server/` that are not application code, each with the reason.
     *
     * @var array<string, string>
     */
    private const NOT_APPLICATION_CODE = [
        'vendor' => 'third-party packages; none of them knows this schema',
        'tests' => 'test fixtures insert into `events` directly on purpose, to set up a store state',
        'storage' => 'runtime output: compiled views, logs, caches',
        'bootstrap/cache' => 'generated by the framework',
        'node_modules' => 'front-end packages',
    ];

    /** Builder methods that write rows, lowercased. */
    private const BUILDER_WRITES = [
        'insert', 'insertorignore', 'insertgetid', 'insertusing', 'insertorignoreusing', 'upsert', 'updateorinsert',
        'update', 'increment', 'decrement', 'incrementeach', 'decrementeach',
    ];

    /** `events`, optionally backticked or schema-qualified, and not the start of a longer name. */
    private const SQL_EVENTS = '(?:`?\w+`?\.)?`?events`?(?![\w`])';

    public function test_nothing_but_the_batch_writer_writes_to_events(): void
    {
        $files = $this->population();

        $this->assertArrayHasKey(self::THE_WRITER, $files,
            'The population does not contain '.self::THE_WRITER.'. The derivation is broken, or the writer moved and this test must move with it.');

        $offenders = [];

        foreach ($files as $relative => $path) {
            if ($relative === self::THE_WRITER) {
                continue;
            }

            foreach (self::writesToEvents((string) file_get_contents($path)) as $finding) {
                $offenders[] = sprintf('server/%s:%d  %s', $relative, $finding['line'], $finding['shape']);
            }
        }

        $this->assertSame([], $offenders, sprintf(
            "These write to `events` outside server/%s:\n  %s\n\n".
            'docs/design/FLEET-STATE.md § 6.5, condition 1: every transaction that inserts into `events` for a seat '.
            "must hold that seat's `seat_state` row lock from its first statement to its commit. BatchWriter::write() ".
            'does; a second writer does not, and its rows can commit below an id the fold has already read past, where '.
            'they are never folded (card#9398). Route the write through BatchWriter, or change the design and this test together.',
            self::THE_WRITER,
            implode("\n  ", $offenders),
        ));
    }

    public function test_the_scanner_finds_the_real_inserter(): void
    {
        $source = (string) file_get_contents($this->serverPath().'/'.self::THE_WRITER);

        $shapes = array_column(self::writesToEvents($source), 'shape');

        $this->assertContains("table('events')->insertOrIgnore()", $shapes,
            'The scanner no longer recognises the insert BatchWriter actually makes. A scanner that misses the real call '.
            'will miss a second one too, so the main test above means nothing until this is fixed.');
    }

    /**
     * @return array<string, array{string, string}>
     */
    public static function writers(): array
    {
        return [
            'insert' => ["DB::table('events')->insert(\$rows);", "table('events')->insert()"],
            'insertOrIgnore, double quotes' => ['DB::table("events")->insertOrIgnore($rows);', "table('events')->insertOrIgnore()"],
            'insertGetId on a named connection' => ["DB::connection('mysql')->table('events')->insertGetId(\$row);", "table('events')->insertGetId()"],
            'insertUsing' => ["DB::table('events')->insertUsing(\$cols, \$select);", "table('events')->insertUsing()"],
            'upsert' => ["DB::table('events')->upsert(\$rows, ['id']);", "table('events')->upsert()"],
            'update after a where with a closure' => [
                "DB::table('events')->where(function (\$q) { \$q->where('id', 1); })->update(['seq' => 2]);",
                "table('events')->update()",
            ],
            'aliased table' => ["DB::table('events as e')->where('e.id', 1)->update(['seq' => 2]);", "table('events')->update()"],
            'builder held in a variable' => [
                "\$q = DB::table('events')->where('seat_ref', 1);\n\$n = \$q->count();\n\$q->insert(\$rows);",
                "table('events')->insert()",
            ],
            'cloned builder' => ["\$q = DB::table('events');\n(clone \$q)->increment('seq');", "table('events')->increment()"],
            'raw INSERT INTO' => ["DB::insert('INSERT INTO events (seat_ref) VALUES (?)', [1]);", 'raw SQL: INSERT INTO events'],
            'raw lowercase insert ignore, backticks' => ["DB::statement('insert ignore into `events` (seat_ref) values (1)');", 'raw SQL: insert ignore into `events`'],
            'raw REPLACE INTO in a heredoc' => ["DB::statement(<<<SQL\n    REPLACE INTO events\n    SELECT * FROM x\n    SQL);", 'raw SQL: REPLACE INTO events'],
            'raw UPDATE' => ["DB::update('UPDATE events SET seq = 1 WHERE id = ?', [1]);", 'raw SQL: UPDATE events'],
            'Eloquent $table' => ["class Row extends Model\n{\n    protected \$table = 'events';\n}", 'Eloquent model on `events` ($table)'],
            'Eloquent inferred from the class name' => ["class Event extends Model\n{\n}", 'Eloquent model on `events` (inferred from class Event)'],
        ];
    }

    #[DataProvider('writers')]
    public function test_the_scanner_finds_each_write_shape(string $body, string $shape): void
    {
        $findings = self::writesToEvents("<?php\n\n".$body."\n");

        $this->assertContains($shape, array_column($findings, 'shape'), 'A planted writer was not reported: '.json_encode($findings));
    }

    /**
     * @return array<string, array{string}>
     */
    public static function nonWriters(): array
    {
        return [
            'a read' => ["\$rows = DB::table('events')->where('seat_ref', 1)->orderBy('id')->get();"],
            'a read through a variable' => ["\$q = DB::table('events');\n\$first = (clone \$q)->value('received_at');"],
            'a delete' => ["DB::table('events')->where('received_at', '<', \$b)->delete();"],
            'a raw delete and a raw read' => ["DB::statement('DELETE FROM events WHERE id < ?', [1]);\nDB::select('SELECT 1 FROM events');"],
            'another table that starts with events' => ["DB::table('events_archive')->insert(\$rows);\nDB::statement('INSERT INTO events_archive SELECT * FROM x');"],
            'an insert into another table that reads events' => ["DB::statement('INSERT INTO batches (n) SELECT COUNT(*) FROM events');"],
            'a mention in a comment' => ["// the only inserter: table('events')->insert\n/* INSERT INTO events */"],
            'an update of another table after a variable of the same name' => ["\$q = DB::table('batches');\n\$q->update(['n' => 1]);"],
            'a model on another table' => ["class Event extends Model\n{\n    protected \$table = 'fleet_events';\n}"],
        ];
    }

    #[DataProvider('nonWriters')]
    public function test_the_scanner_ignores_what_is_not_a_write(string $body): void
    {
        $this->assertSame([], self::writesToEvents("<?php\n\n".$body."\n"));
    }

    /**
     * Every write to `events` in `$source`, in the shapes the class docblock lists.
     *
     * @return list<array{line: int, shape: string}>
     */
    private static function writesToEvents(string $source): array
    {
        $tokens = array_values(array_filter(
            token_get_all($source),
            fn ($t) => ! is_array($t) || ! in_array($t[0], [T_WHITESPACE, T_COMMENT, T_DOC_COMMENT], true),
        ));

        return [
            ...self::builderWrites($tokens),
            ...self::rawSqlWrites($tokens),
            ...self::eloquentModels($tokens),
        ];
    }

    /**
     * `->table('events')` or `::table('events')` followed by a write in its method chain, directly or
     * through a variable it was assigned to in the same file.
     *
     * @param  list<array{int, string, int}|string>  $tokens
     * @return list<array{line: int, shape: string}>
     */
    private static function builderWrites(array $tokens): array
    {
        $findings = [];
        $aliases = [];
        $count = count($tokens);

        for ($i = 0; $i < $count; $i++) {
            if (! self::is($tokens[$i], T_STRING) || strtolower($tokens[$i][1]) !== 'table'
                || ! in_array(self::text($tokens[$i - 1] ?? ''), ['->', '?->', '::'], true)
                || self::text($tokens[$i + 1] ?? '') !== '('
                || ! self::is($tokens[$i + 2] ?? '', T_CONSTANT_ENCAPSED_STRING)
                || ! preg_match('/^([\'"])`?events`?(?:\s+as\s+\w+)?\1$/i', $tokens[$i + 2][1])
                || self::text($tokens[$i + 3] ?? '') !== ')') {
                continue;
            }

            // `$q = DB::table('events')…` makes `$q` an events builder for the rest of the file.
            $start = $i;
            while ($start > 0 && ! in_array(self::text($tokens[$start - 1]), [';', '{', '}', '='], true)) {
                $start--;
            }
            if ($start >= 2 && self::text($tokens[$start - 1]) === '=' && self::is($tokens[$start - 2], T_VARIABLE)) {
                $aliases[$tokens[$start - 2][1]] = true;
            }

            array_push($findings, ...self::chainWrites($tokens, $i + 4, $tokens[$i][2]));
        }

        for ($i = 0; $i < $count; $i++) {
            if (! self::is($tokens[$i], T_VARIABLE) || ! isset($aliases[$tokens[$i][1]])) {
                continue;
            }

            $after = $i + 1;
            if (self::is($tokens[$i - 1] ?? '', T_CLONE) && self::text($tokens[$i + 1] ?? '') === ')') {
                $after = $i + 2;    // `(clone $q)->…`
            }

            array_push($findings, ...self::chainWrites($tokens, $after, $tokens[$i][2]));
        }

        return $findings;
    }

    /**
     * Walk `->name(…)->name(…)` from `$at` and report each write method on it.
     *
     * @param  list<array{int, string, int}|string>  $tokens
     * @return list<array{line: int, shape: string}>
     */
    private static function chainWrites(array $tokens, int $at, int $line): array
    {
        $findings = [];
        $count = count($tokens);

        while ($at + 2 < $count
            && in_array(self::text($tokens[$at]), ['->', '?->'], true)
            && self::is($tokens[$at + 1], T_STRING)
            && self::text($tokens[$at + 2]) === '(') {
            $method = $tokens[$at + 1][1];

            if (in_array(strtolower($method), self::BUILDER_WRITES, true)) {
                $findings[] = ['line' => $line, 'shape' => "table('events')->{$method}()"];
            }

            $depth = 0;
            for ($at += 2; $at < $count; $at++) {
                $text = self::text($tokens[$at]);
                $depth += match ($text) {
                    '(', '[', '{' => 1,
                    ')', ']', '}' => -1,
                    default => 0,
                };
                if (is_array($tokens[$at]) && in_array($tokens[$at][0], [T_CURLY_OPEN, T_DOLLAR_OPEN_CURLY_BRACES], true)) {
                    $depth++;
                }
                if ($depth === 0) {
                    break;
                }
            }
            $at++;
        }

        return $findings;
    }

    /**
     * `INSERT`, `REPLACE` or `UPDATE` on `events` inside a string literal or heredoc.
     *
     * @param  list<array{int, string, int}|string>  $tokens
     * @return list<array{line: int, shape: string}>
     */
    private static function rawSqlWrites(array $tokens): array
    {
        $patterns = [
            '/\b(?:INSERT|REPLACE)(?:\s+(?:LOW_PRIORITY|DELAYED|HIGH_PRIORITY|IGNORE))*(?:\s+INTO)?\s+'.self::SQL_EVENTS.'/i',
            '/\bUPDATE(?:\s+(?:LOW_PRIORITY|IGNORE))*\s+'.self::SQL_EVENTS.'/i',
        ];

        $findings = [];

        foreach ($tokens as $token) {
            if (! is_array($token) || ! in_array($token[0], [T_CONSTANT_ENCAPSED_STRING, T_ENCAPSED_AND_WHITESPACE], true)) {
                continue;
            }

            foreach ($patterns as $pattern) {
                if (preg_match_all($pattern, $token[1], $matches, PREG_OFFSET_CAPTURE)) {
                    foreach ($matches[0] as [$match, $offset]) {
                        $findings[] = [
                            'line' => $token[2] + substr_count(substr($token[1], 0, $offset), "\n"),
                            'shape' => 'raw SQL: '.preg_replace('/\s+/', ' ', $match),
                        ];
                    }
                }
            }
        }

        return $findings;
    }

    /**
     * A class that declares `$table = 'events'`, or a class extending a `…Model` whose name Eloquent
     * would map to `events` and that declares no `$table` of its own.
     *
     * @param  list<array{int, string, int}|string>  $tokens
     * @return list<array{line: int, shape: string}>
     */
    private static function eloquentModels(array $tokens): array
    {
        $findings = [];
        $count = count($tokens);

        for ($i = 0; $i < $count; $i++) {
            if (self::is($tokens[$i], T_VARIABLE) && $tokens[$i][1] === '$table'
                && self::text($tokens[$i + 1] ?? '') === '='
                && self::is($tokens[$i + 2] ?? '', T_CONSTANT_ENCAPSED_STRING)
                && in_array($tokens[$i - 1][0] ?? null, [T_PROTECTED, T_PUBLIC, T_PRIVATE, T_STRING], true)) {
                if (preg_match('/^([\'"])`?events`?\1$/i', $tokens[$i + 2][1])) {
                    $findings[] = ['line' => $tokens[$i][2], 'shape' => 'Eloquent model on `events` ($table)'];
                }

                continue;
            }

            if (! self::is($tokens[$i], T_CLASS) || ! self::is($tokens[$i + 1] ?? '', T_STRING)
                || self::text($tokens[$i + 2] ?? '') !== 'extends'
                || ! preg_match('/Model$/', self::text($tokens[$i + 3] ?? ''))) {
                continue;
            }

            $name = $tokens[$i + 1][1];
            $declaresTable = false;
            for ($j = $i + 4; $j < $count && ! self::is($tokens[$j], T_CLASS); $j++) {
                if (self::is($tokens[$j], T_VARIABLE) && $tokens[$j][1] === '$table' && self::text($tokens[$j + 1] ?? '') === '=') {
                    $declaresTable = true;
                    break;
                }
            }

            if (! $declaresTable && Str::snake(Str::pluralStudly($name)) === 'events') {
                $findings[] = ['line' => $tokens[$i][2], 'shape' => "Eloquent model on `events` (inferred from class {$name})"];
            }
        }

        return $findings;
    }

    /**
     * @param  array{int, string, int}|string  $token
     */
    private static function is(array|string $token, int $id): bool
    {
        return is_array($token) && $token[0] === $id;
    }

    /**
     * @param  array{int, string, int}|string  $token
     */
    private static function text(array|string $token): string
    {
        return is_array($token) ? $token[1] : $token;
    }

    /**
     * @return array<string, string> path relative to `server/` => absolute path
     */
    private function population(): array
    {
        $server = $this->serverPath();
        $excluded = array_map(fn ($d) => $server.'/'.$d.'/', array_keys(self::NOT_APPLICATION_CODE));
        $files = [];

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveCallbackFilterIterator(
                new \RecursiveDirectoryIterator($server, \FilesystemIterator::SKIP_DOTS),
                fn (\SplFileInfo $f) => ! $f->isDir() || ! in_array($f->getPathname().'/', $excluded, true),
            ),
        );

        foreach ($iterator as $file) {
            if ($file->getExtension() === 'php') {
                $files[substr($file->getPathname(), strlen($server) + 1)] = $file->getPathname();
            }
        }

        return $files;
    }

    private function serverPath(): string
    {
        return dirname(__DIR__, 3);
    }
}
