<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Laravel\Fortify\Contracts\TwoFactorAuthenticationProvider;
use Laravel\Fortify\Fortify;
use Laravel\Fortify\RecoveryCode;

/**
 * @extends Factory<User>
 */
class UserFactory extends Factory
{
    /**
     * The hash every factory-made account carries, minted once per run from `password()` below.
     */
    protected static ?string $password;

    /**
     * ⛔ THE PLAINTEXT, MINTED PER RUN AND NEVER WRITTEN DOWN — card#9070's second review round.
     *
     * This used to be the literal `password`, hashed. That literal is what made
     * `database/seeders/DatabaseSeeder.php`'s stock body a publicly known credential behind the
     * login page of any host that ran `php artisan db:seed`, and the fix chosen for it was to move
     * this namespace into composer's `autoload-dev` block plus a DOCUMENTED
     * `composer install --no-dev` obligation on deployed hosts (`docs/PLAN.md § 5`).
     *
     * That fix closes the class only on hosts that honour the flag, and nothing reds if one never
     * does — no `bin/deploy.sh` exists yet to honour it (D-08: the host is not provisioned). A
     * random value closes it IN CODE, on every host, whatever flags the installer used, and costs
     * three call-sites to adopt. So the `--no-dev` obligation stays, and it is now defence in depth
     * rather than the whole defence.
     *
     * ⚠ IT IS EXPOSED AS A METHOD RATHER THAN A CONSTANT because it cannot be a constant and still
     * be random. A test that needs to authenticate a factory-made account reads
     * `UserFactory::password()`; nothing in the repository ever states the value.
     */
    protected static ?string $plaintext;

    /** The plaintext behind every factory-made account for the life of this process. */
    public static function password(): string
    {
        return static::$plaintext ??= Str::random(40);
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->name(),
            'email' => fake()->unique()->safeEmail(),
            'email_verified_at' => now(),
            'password' => static::$password ??= Hash::make(static::password()),
            'remember_token' => Str::random(10),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            'email_verified_at' => null,
        ]);
    }

    /**
     * A user who has completed second-factor enrolment.
     *
     * The secret is generated by the same provider the enrolment flow uses and encrypted the
     * same way, so a test in this state exercises the real decrypt path rather than a
     * placeholder. It is generated rather than written down deliberately: a base32 TOTP
     * secret committed to a repository is a credential-shaped literal that every secret
     * scanner will flag forever, and adding it to a scanner's allowlist is how allowlists
     * start absorbing real findings.
     */
    public function twoFactorConfirmed(): static
    {
        return $this->state(fn (array $attributes) => [
            'two_factor_secret' => Fortify::currentEncrypter()->encrypt(
                app(TwoFactorAuthenticationProvider::class)->generateSecretKey()
            ),
            'two_factor_recovery_codes' => Fortify::currentEncrypter()->encrypt(json_encode(
                Collection::times(8, fn () => RecoveryCode::generate())->all()
            )),
            'two_factor_confirmed_at' => now(),
        ]);
    }

    /**
     * A user who is authenticated but has NOT completed enrolment — the state Fortify's
     * login pipeline lets through on a password alone.
     */
    public function twoFactorUnenrolled(): static
    {
        return $this->state(fn (array $attributes) => [
            'two_factor_secret' => null,
            'two_factor_recovery_codes' => null,
            'two_factor_confirmed_at' => null,
        ]);
    }
}
