<?php

namespace Tests\Feature\Floor;

use Tests\TestCase;

/**
 * **§ 5.7's bound on the coordination envelopes the client protocol holds** — `docs/design/FLOOR.md
 * § 5.7`, § 12's *Held coordination envelopes* row and § 14 item 25, built at Appendix B row 8 because
 * that step's page is the first to stay open. card#7341 step 8.
 *
 * ─────────────────────────────────────────────────────────────────────────────────────────────
 * ⛔ THE FIGURE IS § 12's, READ HERE, AND THE MODULE's CONSTANT IS HELD TO IT. A bound nobody
 * re-derives is a bound that drifts from the document that chose it.
 *
 * ⛔ EACH CLAUSE OF THE RULING HAS A RED WATCHED TO FAIL: no eviction at all (the list grows past the
 * cap), eviction by single posts (a thread is left without its `coord.thread`), an oversize thread
 * whose shrunken count is not marked (*N+* missing), and the animated-posts record left untrimmed (a
 * post redelivered after its thread was evicted animates nothing — the stated cost inverted into a
 * leak).
 *
 * ⛔ THE ENVELOPES PAST THE FIXTURE's OWN ARE GENERATED BY `coord-cap-probe.mjs`'s ONE RULE, from the
 * counts below — a thousand envelopes spelled out in a fixture is a file nobody reads.
 */
class TheCoordinationEnvelopesAreHeldToTheirCapTest extends TestCase
{
    use DrivesTheFleetClientModule;

    /** RED — no eviction: the list is never cut. */
    private const NO_EVICTION = ['fleet-client.js', 'while (this.#coord.length > COORD_CAP) {', 'while (false) {'];

    /** RED — single-post eviction: the oldest envelope goes, whatever thread it belongs to. */
    private const SINGLE_POSTS = ['fleet-client.js', '            if (newest.size > 1) {', "            if (newest.size > 1) {\n                this.#coord.shift();\n\n                continue;\n            }\n\n            if (false) {"];

    /** RED — the oversize thread's count is not marked as a lower bound. */
    private const UNMARKED = ['fleet-client.js', "                this.#coordTruncated.add(threadOf(this.#coord[drop]));\n", ''];

    /** RED — the animated-posts record is never trimmed. */
    private const UNTRIMMED = ['../floor/floor-screen.js', '                this.#drawn.delete(ref);', ''];

    public function test_the_modules_cap_is_section_12s_figure(): void
    {
        $this->assertSame(1, preg_match('/^\| Held coordination envelopes \| \*\*([\d,]+) envelopes\*\*/m', $this->floorMd(), $m),
            '§ 12\'s *Held coordination envelopes* row did not parse');
        $this->assertSame(1, preg_match('/export const COORD_CAP = (\d+);/', (string) file_get_contents($this->moduleDir().'/fleet-client.js'), $c));
        $this->assertSame((int) str_replace(',', '', $m[1]), (int) $c[1], 'the client protocol\'s cap is not § 12\'s figure');
    }

    public function test_green_the_least_recently_received_thread_leaves_whole(): void
    {
        $this->assertSame([], $this->wholeThreadDefects($this->drive($this->twoThreads())));
    }

    public function test_green_one_thread_over_the_cap_keeps_its_thread_object_and_counts_its_beads_as_a_lower_bound(): void
    {
        $this->assertSame([], $this->oversizeDefects($this->drive($this->oneThread())));
    }

    public function test_green_the_animated_posts_record_is_trimmed_to_the_posts_still_held(): void
    {
        $this->assertSame([], $this->trimDefects($this->drive($this->redelivery())));
    }

    public function test_red_no_eviction_is_caught(): void
    {
        $this->assertArrayHasKey('cap', $this->wholeThreadDefects($this->drive($this->twoThreads(), $this->mutatedModules(self::NO_EVICTION))));
    }

    public function test_red_single_post_eviction_is_caught(): void
    {
        $this->assertArrayHasKey('whole', $this->wholeThreadDefects($this->drive($this->twoThreads(), $this->mutatedModules(self::SINGLE_POSTS))));
    }

    public function test_red_an_unmarked_lower_bound_is_caught(): void
    {
        $this->assertArrayHasKey('beads', $this->oversizeDefects($this->drive($this->oneThread(), $this->mutatedModules(self::UNMARKED))));
    }

    public function test_red_an_untrimmed_record_is_caught(): void
    {
        $this->assertArrayHasKey('redelivered', $this->trimDefects($this->drive($this->redelivery(), $this->mutatedModules(self::UNTRIMMED))));
    }

    private function cap(): int
    {
        preg_match('/export const COORD_CAP = (\d+);/', (string) file_get_contents($this->moduleDir().'/fleet-client.js'), $c);

        return (int) $c[1];
    }

    /** Thread A — one object and 10 rounds — then thread B with enough rounds to pass the cap. */
    private function twoThreads(): array
    {
        return ['steps' => [
            ['generate' => ['t' => 'coord.thread', 'thread_ref' => 'A', 'install_id' => 'aimla', 'count' => 1]],
            ['generate' => ['t' => 'coord.round', 'thread_ref' => 'A', 'install_id' => 'aimla', 'count' => 10, 'post_prefix' => 'A-']],
            ['generate' => ['t' => 'coord.thread', 'thread_ref' => 'B', 'install_id' => 'aimla', 'count' => 1]],
            ['generate' => ['t' => 'coord.round', 'thread_ref' => 'B', 'install_id' => 'aimla', 'count' => $this->cap() - 5, 'post_prefix' => 'B-']],
        ]];
    }

    /** One thread alone past the cap by 200 rounds. */
    private function oneThread(): array
    {
        return ['steps' => [
            ['generate' => ['t' => 'coord.thread', 'thread_ref' => 'A', 'install_id' => 'aimla', 'count' => 1]],
            ['generate' => ['t' => 'coord.round', 'thread_ref' => 'A', 'install_id' => 'aimla', 'count' => $this->cap() + 200, 'post_prefix' => 'A-']],
        ]];
    }

    /**
     * `fx-coord`'s own thread on the floor — its R1 is a broadcast from a resolving origin, so A20
     * fires once — then a filler thread that evicts it, then R1 delivered again.
     */
    private function redelivery(): array
    {
        $fixture = $this->fixture('coord');
        $envelopes = array_map(static fn (array $m): array => $m['envelope'], $fixture['messages']);
        $r1 = array_values(array_filter($envelopes, static fn (array $e): bool => ($e['coord_round']['post_ref'] ?? null) === 'R1'))[0];

        return [
            'http' => $fixture['http'],
            'floor' => $fixture['floor']['key'],
            'steps' => [
                ['deliver' => $envelopes, 'render' => true],
                ['generate' => ['t' => 'coord.round', 'thread_ref' => 'FILLER', 'install_id' => 'aimla', 'count' => $this->cap(), 'post_prefix' => 'F-'], 'render' => true],
                ['deliver' => [$r1], 'render' => true],
            ],
        ];
    }

    private function drive(array $payload, ?string $dir = null): array
    {
        $payload['http'] ??= $this->fixture('coord')['http'];
        $payload['floor'] ??= null;

        $script = __DIR__.'/coord-cap-probe.mjs';
        $process = proc_open(['node', $script, $dir ?? $this->moduleDir()], [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);

        $this->assertIsResource($process, 'node could not be started');
        fwrite($pipes[0], json_encode($payload));
        fclose($pipes[0]);
        $out = stream_get_contents($pipes[1]);
        $err = stream_get_contents($pipes[2]);
        $code = proc_close($process);

        $this->assertSame(0, $code, "the coord-cap probe failed: {$err}");

        return json_decode((string) $out, true);
    }

    /** @return array<string, string> */
    private function wholeThreadDefects(array $out): array
    {
        $final = end($out['steps']);
        $defects = [];

        if ($final['held'] > $this->cap()) {
            $defects['cap'] = "{$final['held']} envelopes held over a cap of {$this->cap()}";
        }

        // A left WHOLE — none of its envelopes — and B complete: its object and every round.
        if (isset($final['threads']['A'])) {
            $defects['whole'] = 'thread A was cut rather than evicted whole: '.json_encode($final['threads']['A']);
        }

        foreach ($final['threads'] as $ref => $t) {
            if ($t['threads'] !== 1) {
                $defects['whole'] = "thread {$ref} is held without its `coord.thread`";
            }
        }

        if (($final['threads']['B']['rounds'] ?? 0) !== $this->cap() - 5 || $final['truncated'] !== []) {
            $defects['survivor'] = 'the surviving thread is not complete: '.json_encode($final['threads']['B'] ?? null);
        }

        return $defects;
    }

    /** @return array<string, string> */
    private function oversizeDefects(array $out): array
    {
        $final = end($out['steps']);
        $defects = [];

        if ($final['held'] !== $this->cap()) {
            $defects['cap'] = "{$final['held']} envelopes held, not the cap's {$this->cap()}";
        }

        if (($final['threads']['A']['threads'] ?? 0) !== 1) {
            $defects['thread'] = 'the oversize thread lost its `coord.thread`';
        }

        // The oldest rounds went: the first held is round 202 of 1,200.
        if (($final['threads']['A']['first_post'] ?? null) !== 'A-202') {
            $defects['oldest'] = 'the rounds dropped are not the oldest: first held '.json_encode($final['threads']['A']['first_post'] ?? null);
        }

        if (($final['beads']['A'] ?? null) !== ($this->cap() - 1).'+') {
            $defects['beads'] = 'the bead count is not the lower bound *N+*: '.json_encode($final['beads']['A'] ?? null);
        }

        return $defects;
    }

    /** @return array<string, string> */
    private function trimDefects(array $out): array
    {
        [$first, $evicted, $again] = $out['steps'];
        $defects = [];

        $this->assertGreaterThan(0, $first['animated']['A20'], 'fx-coord fired no A20 — the redelivery clause cannot fail');

        if ($evicted['held'] > $this->cap() || isset($evicted['threads']['T1'])) {
            $defects['evicted'] = 'the fixture\'s thread was not evicted by the filler: '.json_encode($evicted['threads']['T1'] ?? null);
        }

        // The stated cost, and the evidence the record was trimmed: R1, redelivered after its thread
        // left the held population, animates again.
        if ($again['animated']['A20'] !== $first['animated']['A20'] + 1) {
            $defects['redelivered'] = "R1 redelivered after eviction took the A20 rows from {$first['animated']['A20']} to {$again['animated']['A20']}, not one more";
        }

        return $defects;
    }
}
