#!/usr/bin/env python3
"""D1 verification gate: bind this document's harness facts to the installed harness binary.

Two bindings, one rung apart:

  * KEY NAMES (rounds 3+).  Every fixture key in the appendix must be a key the installed
    build's own payload schema declares for that hook.
  * ENUM VALUE SETS (round 4).  Every harness-sourced enum's value set is re-derived from
    the binary and asserted against EVERY place the document states it.  Round 3 bound key
    names and built a guard for them; it did not bind value sets, which is how a
    `notification_type` row carrying 14 of the build's 16 declared members survived three
    review rounds -- omitting exactly the two the `elicitation` branch depends on.

Ground truth is the INSTALLED HARNESS BINARY's own declarations, re-derived on every run.
Nothing here is a stored FACT -- not a number, not a key name, not a minified identifier --
and every extractor carries a control that ABORTS rather than reporting clean when it cannot
discriminate (canon #9: a check that cannot fail is a decoration).  "Number" is what that
sentence said until card#7947, and a transcribed list of the harness's nine COMMON payload
key names sat below it the whole time, backing most of the fixture-key assertions in § 1.

WHICH build is ground truth is D1's fact, not this tool's: the version is READ from the
document's own declaration sites and this file states it nowhere.  A version typed here
would be a restatement with neither a pointer nor a guard -- the exact defect class D1
§ 6.0 is written about, one level up.  Likewise nothing here is pinned to a minified
identifier: those are regenerated by the bundler on every build (`literal()` was `Ht` at
2.1.240, `o` at 2.1.243-2.1.246, `n` at 2.1.247), so a pinned one is a second dead pin
wearing a different costume.  Shapes are matched; names are derived.

Environment:
  MEZZ_HARNESS_BIN       path to the harness bundle to read as ground truth.  Overrides
                         the default and is NAMED on every run, together with the fact
                         that it is not the build D1 declares.
  MEZZ_CLAUDE_VERSIONS   directory holding the installed bundles.  Default: the directory
                         the `claude` on PATH resolves into, else ~/.local/share/claude/versions.
"""
import os, re, shutil, sys, pathlib
from functools import lru_cache

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from d1_appendix import AppendixError, parse_appendix   # the ONE § 17 parser (see § 1 below)

ROOT = pathlib.Path(__file__).parent.parent.parent
DOC  = ROOT / "docs/design/EVENT-SCHEMA.md"
fail, notes = [], []

# ---------- which build is ground truth: READ from D1, never restated here ---------
# D1 states its capture build in five places (verified 2026-08-27: § preamble, § 6.0 twice,
# § 14's provenance row, § 17's capture-seat row).  All five are load-bearing (a reader who
# lands on any one of them takes it as the version its MEASURED facts hold at), so the
# derivation requires them to agree: a run over a document whose sites disagree cannot
# say which build it is binding to and reports that rather than picking one.
DECLARED_BUILD_SITES = {
    "the § preamble status block":
        r"captured from Claude Code \*\*(\d+\.\d+\.\d+)\*\*",
    "§ 6.0's measurement-of-record paragraph":
        r"were captured on \*\*[\d-]+\*\* from \*\*Claude Code (\d+\.\d+\.\d+)\*\* on Linux",
    "§ 6.0's re-capture obligation":
        r"Every MEASURED fact in this document is versioned to (\d+\.\d+\.\d+)",
    "§ 14's provenance row":
        r"\| Harness build the MEASURED facts are pinned to \| Claude Code \*\*(\d+\.\d+\.\d+)\*\*",
    "§ 17's capture-seat row":
        r"\| Harness \| \*\*Claude Code (\d+\.\d+\.\d+)\*\*",
}

def declared_build(doc_text):
    """The build D1 says its MEASURED facts were captured at, or None with a reason."""
    found, missing = {}, []
    for site, pat in DECLARED_BUILD_SITES.items():
        m = re.search(pat, doc_text)
        if m:
            found[site] = m.group(1)
        else:
            missing.append(site)
    if missing:
        return None, ("D1's declared harness build cannot be read at: "
                      + ", ".join(missing)
                      + " — the ground-truth build cannot be derived, so this check reports "
                        "nothing rather than binding to a build nobody declared")
    if len(set(found.values())) != 1:
        return None, ("D1 declares more than one capture build — "
                      + "; ".join(f"{s} says {v}" for s, v in sorted(found.items()))
                      + " — re-mark every site to the build the capture was actually run at")
    return next(iter(found.values())), None

def versions_dir():
    """Where the installed bundles live — derived, not a path into one user's home."""
    env = os.environ.get("MEZZ_CLAUDE_VERSIONS")
    if env:
        return pathlib.Path(env)
    exe = shutil.which("claude")
    if exe:
        return pathlib.Path(exe).resolve().parent
    return pathlib.Path.home() / ".local/share/claude/versions"

DOCTEXT = DOC.read_text()
DECLARED, declared_err = declared_build(DOCTEXT)

BIN_OVERRIDE = os.environ.get("MEZZ_HARNESS_BIN")
if BIN_OVERRIDE:
    BIN = pathlib.Path(BIN_OVERRIDE)
    # An override NAMES what it bound to, every run.  Silently re-binding to whatever a
    # box happens to carry converts "these facts are true of <declared>" into "true of
    # today's build" — a strictly weaker claim that would go GREEN on a build whose enums
    # have genuinely moved, which is the false clean this tool exists to prevent.
    notes.append(f"⚠ ground truth OVERRIDDEN via MEZZ_HARNESS_BIN → {BIN}")
    if DECLARED and BIN.name != DECLARED:
        notes.append(f"⚠ D1's MEASURED facts are declared against {DECLARED}; a PASS here is "
                     f"evidence about {BIN.name}, NOT about {DECLARED}")
elif DECLARED:
    BIN = versions_dir() / DECLARED
else:
    BIN = None

# ---------- re-derive the harness ground truth (never a stored figure) -------------
# ONE spelling of "a payload field name", used by both entry points below.  Two spellings
# are free to disagree about what a field is, and the first thing that produces is one
# walker seeing a key the other one drops.
_FIELD     = r"[a-z_]+"
_FIELD_RE  = re.compile(r",(%s):" % _FIELD)      # `,key:` — every field after the first
_FIRST_RE  = re.compile(r"\{\s*(%s):" % _FIELD)  # `{key:` — the first, which has no comma

def _keys_after(s, start):
    """Collect `,key:` at brace/paren depth 0, walking forward from a declaration.

    `_FIELD_RE.match(s, i)`, never `re.match(pat, s[i:])`: the slice copies the whole
    remaining bundle -- ~47 MB per depth-0 comma here -- and this walker is called once per
    hook declaration and once per base schema. Same defect as the one `_assignments` below
    records; it just wore a slice instead of an unanchored `\\b`.
    """
    d = i = 0; i = start; out = set()
    while i < len(s) and i < start + 4000:
        c = s[i]
        if c in "([{":
            d += 1
        elif c in ")]}":
            if d == 0:
                break
            d -= 1
        elif c == "," and d == 0:
            m = _FIELD_RE.match(s, i)
            if m:
                out.add(m.group(1))
        i += 1
    return out

TXT = BIN.read_bytes().decode("latin-1") if (BIN and BIN.exists()) else ""

HOOK_DECL = {}          # hook -> [offset just past its `hook_event_name:<lit>("X")`]
HOOK_COMMON = {}        # hook -> the field names it inherits from the build's base schema

# The wrapper is zod's `literal()`, whose minified NAME changes every build.  Match the
# shape and let the control below prove the match discriminates.  The discriminant key's
# own name is a CAPTURE, not a second spelling: what goes into each hook's key set is the
# text this pattern matched in the bundle, so a build that renamed it yields zero hooks
# and the control below aborts, rather than the sets quietly carrying a dead name.
HOOK_DECL_RE = re.compile(r'(hook_event_name):[A-Za-z_$][\w$]*\("([A-Za-z]+)"\)')

# ---------- the BASE payload schema: derived, never transcribed -------------------
# Every hook declaration in the builds measured has the shape
#   <base>().and(<obj>({hook_event_name:<lit>("X"), ...hook-specific fields...}))
# so the fields EVERY hook carries -- the session/cwd/agent/effort family -- are declared
# exactly once, on `<base>`, and `_keys_after` above only ever walks the hook-specific half.
# Those common fields back most of this gate's fixture-key assertions, and until card#7947
# they were a hand-transcribed list sitting in this file: a stored fact backing the
# MAJORITY of the population, checked against nothing.  Rename one in the harness and every
# assertion resting on it would have kept passing against a name the build no longer
# declares -- the check could not fail, which is the decoration canon #9 names.  Derived
# now, from the same reference site the hook keys come from.
BASE_AND_RE  = re.compile(r'([A-Za-z_$][\w$]*)\(\)\.and\([A-Za-z_$][\w$]*\(\{$')
BASE_DECL_RE = re.compile(r'\s*[A-Za-z_$][\w$]*\(\(\)\s*=>\s*[A-Za-z_$][\w$]*\(\{')

@lru_cache(maxsize=None)
def base_schema_keys(name, near):
    """The field names the base schema `<name>` declares, read in `near`'s own module.

    `<name>` is a generated identifier -- `h` at 2.1.247 -- and is derived from the
    reference site for the same reason no other minified name is pinned here.  Resolution
    is MODULE-SCOPED like § 6's: `h=` has 5009 assignments in a 2.1.247 bundle, so the
    first one in file order is some other module's.

    An EMPTY resolution is no answer, never "this build declares no common fields": that
    would silently narrow every hook's key set and turn a renamed field into a clean run.
    """
    for pos in _bindings_near(name, near):
        m = BASE_DECL_RE.match(TXT[pos:pos + 200])
        if not m:
            continue
        brace = pos + m.end() - 1
        keys = _keys_after(TXT, brace + 1)
        first = _FIRST_RE.match(TXT, brace)     # `_keys_after` reads `,key:` — the first
        if first:                               # field of an object literal has no comma
            keys.add(first.group(1))
        if keys:
            return frozenset(keys)
    raise ValueError(
        f"the hook declarations name {name!r} as the schema their common fields come from, "
        f"but no `{name}=` in the module that references it declares an object with fields "
        f"-- the common key names cannot be re-derived from this build, so this reports "
        f"nothing rather than binding to a list nobody read out of the binary")

def harness_truth():
    hooks, bases, unbased = {}, {}, []
    for m in HOOK_DECL_RE.finditer(TXT):
        key, hook = m.group(1), m.group(2)
        HOOK_DECL.setdefault(hook, []).append(m.end())
        hooks.setdefault(hook, set()).update(_keys_after(TXT, m.end()) | {key})
        # BASE_AND_RE is `$`-anchored, so this window only has to be longer than the prefix
        # it matches (`h().and(t({` is 11 chars at 2.1.247); it is not a search radius.
        b = BASE_AND_RE.search(TXT[max(0, m.start() - 64):m.start()])
        if b:
            bases.setdefault(hook, set()).add((b.group(1), m.start()))
        else:
            unbased.append(hook)
    # A declaration this does not recognise is NOT a hook without common fields.  Folding
    # the common set into it anyway would assert keys the build may not declare; leaving
    # them out would red its fixtures for the wrong reason.  Neither is a measurement, so
    # name what cannot be read and stop.
    if unbased:
        raise SystemExit(
            "harness-truth extractor: hook declaration(s) "
            f"{sorted(set(unbased))} are not of the `<base>().and(<obj>({{hook_event_name:…}}))` "
            "form this derives the common payload fields from. The bundler's shape changed; "
            "teach BASE_AND_RE the new one. This does not guess which common fields those "
            "hooks carry.")
    # CONTROL (canon #9): the extractor must be shown capable of the other answer, or its
    # "every key resolves" verdict is a decoration.  SessionStart's key IS `source`; the
    # string `session_start_reason` occurs nowhere in this build.  If the extractor cannot
    # tell those apart it cannot tell anything apart, so refuse to report a clean.
    ss = hooks.get("SessionStart", set())
    if "source" not in ss or "session_start_reason" in ss:
        raise SystemExit("harness-truth extractor failed its control: "
                         f"SessionStart keys = {sorted(ss)}")
    out, base_only = {}, set()
    for hook, keys in hooks.items():
        common = frozenset().union(*(base_schema_keys(n, at) for n, at in bases[hook]))
        HOOK_COMMON[hook] = common
        base_only |= common - keys
        out[hook] = keys | common
    # CONTROL for the base resolver, in two legs that name no field -- a control spelled as
    # `"cwd" in common` would be the transcribed list back again, wearing an assert.
    #   1. NEGATIVE: a builder name the module does not declare must RAISE.  A resolver that
    #      answers for a name that is not there would "confirm" any name, including the one
    #      a renamed field left behind.
    probe = sorted({n for s in bases.values() for n, _ in s})[0] + "_no_such_builder"
    at = next(iter(next(iter(bases.values()))))[1]
    try:
        got = base_schema_keys(probe, at)
    except ValueError:
        pass
    else:
        raise SystemExit(f"base-schema extractor control FAILED: fabricated builder {probe!r} "
                         f"resolved to {sorted(got)!r} instead of raising -- it would "
                         f"'confirm' whatever name the hook declarations happened to carry")
    #   2. LOAD-BEARING: the base must contribute at least one field NO hook declares in its
    #      own half.  If every common field were also a hook-specific one, this resolver
    #      would be indistinguishable from returning nothing, and a rename inside it would
    #      hide behind the hook halves.
    if not base_only:
        raise SystemExit("base-schema extractor control FAILED: every field it resolved is "
                         "also declared by a hook's own half, so nothing in this run "
                         "distinguishes it from an extractor that resolved nothing")
    notes.append(f"common payload fields re-derived from the build's base schema: "
                 f"{len(frozenset().union(*HOOK_COMMON.values()))} across {len(out)} hooks, "
                 f"{len(base_only)} of them declared by no hook's own half "
                 f"(fabricated-builder control raised)")
    return out

# ---------- re-derive harness ENUM VALUE SETS from the binary ----------------------
# Identifier resolution is MODULE-SCOPED, never global-first-match.  The bundler's names
# are per-module and heavily reused -- `Qs` has 45 assignments and `O` has 1520 in one
# 2.1.247 bundle -- so the first `<name>=[...]` in file order is some other module's
# array.  This is not a robustness nicety: global first-match resolved
# `Notification.notification_type` to a 2-member set at 2.1.247 and to a 39-member list of
# SHELL DOTFILE NAMES at 2.1.243, either of which reads as "the harness changed this enum"
# and is a fabricated fact -- exactly the false MEASURED this tool exists to prevent.  It
# was right at 2.1.240 by luck, and the luck was the whole binding.
#
# Modules are delimited by the bundler's own per-module banner, and a name the referencing
# module does not itself assign is followed through its `import{EXPORTED as name}` to the
# `export{LOCAL as EXPORTED}` in the declaring module -- the notification set lives two
# modules away from the matcher metadata that spreads it, on every build measured.
MODULE_BANNER = "// @bun @bytecode"

@lru_cache(maxsize=None)
def _module_bounds(off):
    """[start, end) of the bundled module containing `off`."""
    lo = TXT.rfind(MODULE_BANNER, 0, off)
    hi = TXT.find(MODULE_BANNER, off)
    return (lo if lo >= 0 else 0), (hi if hi >= 0 else len(TXT))

def _literal_array(expr, near, depth=0):
    """Resolve a JS array literal, following `...spread` identifiers and one-line consts."""
    if depth > 6:
        raise ValueError("array resolution too deep")
    out = []
    for tok in re.finditer(r'"([^"]*)"|\.\.\.([A-Za-z_$][\w$]*)', expr):
        if tok.group(1) is not None:
            out.append(tok.group(1))
        else:
            out.extend(_ident_array(tok.group(2), near, depth + 1))
    return out

@lru_cache(maxsize=None)
def _assignments(name):
    """Offsets just past each `<name>=` in the bundle, at an identifier boundary.

    A literal `str.find` scan, not `re.search(r'\\b<name>\\s*=')`: an unanchored `\\b`
    pattern over a 340 MB bundle costs ~13 s per lookup and is what made an earlier
    version of this tool take minutes.
    """
    i, out = 0, []
    tok = name + "="
    while True:
        i = TXT.find(tok, i)
        if i < 0:
            return tuple(out)
        if i == 0 or not (TXT[i - 1].isalnum() or TXT[i - 1] in "_$."):
            out.append(i + len(tok))
        i += len(tok)

_SCOPE = "module"       # flipped to "global" ONLY by the control below

def _bindings_near(name, near):
    """This identifier's assignments inside `near`'s own module, nearest site first."""
    if _SCOPE == "global":
        return _assignments(name)          # the defective strategy, for the control
    lo, hi = _module_bounds(near)
    return sorted((p for p in _assignments(name) if lo <= p < hi), key=lambda p: abs(p - near))

def _through_import(name, near):
    """Follow `import{EXPORTED as name}` out to the `export{LOCAL as EXPORTED}` that declares it.

    Returns `(local_name, offset_of_the_export)` or None.  The exported name is generated
    and unique to the bundle, so the export site is unambiguous.
    """
    if _SCOPE == "global":
        return None
    lo, hi = _module_bounds(near)
    m = re.search(r'[{,]([A-Za-z_$][\w$]*) as %s[,}]' % re.escape(name), TXT[lo:hi])
    if not m:
        return None
    em = re.search(r'[{,]([A-Za-z_$][\w$]*) as %s[,}]' % re.escape(m.group(1)), TXT)
    if not em:
        return None
    return em.group(1), em.start()

@lru_cache(maxsize=None)
def _ident_array(name, near, depth=0):
    """`name=["a","b"]`, resolved in the module that referenced it.

    An EMPTY resolution is treated as no resolution, never as an answer: `X=[]` is a
    collision with some other module's empty array, and returning it would report a
    zero-member enum as a fact.
    """
    if depth > 6:
        raise ValueError("array resolution too deep")
    for pos in _bindings_near(name, near):
        m = re.match(r'\s*(\[[^\]]*\])', TXT[pos:pos + 4000])
        if m:
            got = _literal_array(m.group(1), pos, depth)
            if got:
                return tuple(got)
    via = _through_import(name, near)
    if via:
        return _ident_array(via[0], via[1], depth + 1)
    raise ValueError(f"identifier {name!r} is assigned no non-empty array literal in the "
                     f"module that references it, and no import binding leads to one")

def _resolve_expr(expr, near, depth=0):
    """Resolve a zod-ish field expression to its literal member list.

    Handles `enum([...])`, `enum(IDENT)`, and `IDENT()` -> `lazy(()=>...)` indirection.
    Wrapper NAMES are never matched — the bundler regenerates them every build.
    """
    if depth > 6:
        raise ValueError("expression resolution too deep")
    expr = expr.strip()
    m = re.match(r'^[A-Za-z_$][\w$]*\(\s*(\[[^\]]*\])', expr)          # a(["x","y"])
    if m:
        return tuple(_literal_array(m.group(1), near, depth))
    m = re.match(r'^[A-Za-z_$][\w$]*\(\s*([A-Za-z_$][\w$]*)\s*\)', expr)  # a(Vs)
    if m:
        try:
            return _ident_array(m.group(1), near, depth + 1)
        except ValueError:
            pass
    m = re.match(r'^([A-Za-z_$][\w$]*)\(\s*\)', expr)                  # Qs()
    if m:
        for pos in _bindings_near(m.group(1), near):
            d = re.match(r'\s*[A-Za-z_$][\w$]*\(\(\)\s*=>\s*(.{0,600})', TXT[pos:pos + 800], re.S)
            if not d:
                continue
            try:
                return _resolve_expr(d.group(1), pos, depth + 1)
            except ValueError:
                continue
        raise ValueError(f"cannot resolve {m.group(1)!r}")
    raise ValueError(f"unrecognised value-set expression: {expr[:60]!r}")

@lru_cache(maxsize=None)
def binary_value_set(spec):
    """`Hook.field` -> the member list this build declares for it."""
    hook, _, field = spec.partition(".")
    if hook == "Notification" and field == "notification_type":
        # not a payload enum -- the payload types it as a plain string.  The build's own
        # matcher metadata is what declares the routed set.
        m = re.search(r'fieldToMatch:"notification_type",values:(\[[^\]]*\])', TXT)
        if not m:
            raise ValueError("Notification matcher metadata not found in this build")
        return tuple(_literal_array(m.group(1), m.start(1)))
    # reuse the single full-file pass harness_truth() already made, rather than re-scanning
    # 340 MB per lookup -- a gate slow enough to skip is a gate that decays.
    if hook not in HOOK_DECL:
        raise ValueError(f"hook {hook!r} is not declared in this build")
    last = None
    for pos in HOOK_DECL[hook]:
        f = re.search(r'[,{]%s:(.{0,400})' % re.escape(field), TXT[pos:pos + 600])
        if not f:
            continue
        try:
            return tuple(_resolve_expr(f.group(1), pos + f.start(1)))
        except ValueError as e:
            last = e
    if last:
        raise last
    raise ValueError(f"{hook} declares no field {field!r} in this build")

def value_set_controls():
    """Show the resolver capable of the other answer, or abort rather than report clean."""
    a = set(binary_value_set("SessionStart.source"))
    b = set(binary_value_set("PreCompact.trigger"))
    if not a or not b:
        raise SystemExit("value-set extractor control FAILED: a resolved set is empty")
    if a == b:
        raise SystemExit("value-set extractor control FAILED: two different declarations "
                         f"resolved to the same set {sorted(a)} -- it cannot discriminate")
    try:
        got = binary_value_set("SessionStart.no_such_field_at_all")
    except ValueError:
        pass
    else:
        raise SystemExit("value-set extractor control FAILED: a fabricated field resolved "
                         f"to {got!r} instead of raising -- it would 'confirm' anything")
    return len(a), len(b)

# ---------- bind, or red with ONE actionable line ---------------------------------
# Fail-closed is the point: with no binary the declared-hook set is empty and EVERY
# fixture and enum row would fail against it — one cause wearing thirty costumes, and a
# future reader "fixing" the document to match would delete true facts.  So when ground
# truth is unavailable this reports exactly why, and stops.
if declared_err:
    print(f"FAILURES (1):\n  - {declared_err}")
    sys.exit(1)
if not BIN.exists():
    installed = sorted(p.name for p in versions_dir().glob("*")) if versions_dir().is_dir() else []
    print("FAILURES (1):")
    print(f"  - D1's harness facts are declared MEASURED against Claude Code {DECLARED}, which is "
          f"not installed at {BIN} — ground truth cannot be re-derived, so this check reports "
          f"nothing rather than a false clean. Installed here: "
          f"{', '.join(installed) or 'none found'}. FIX: re-run D1 § 6.0's capture against an "
          f"installed build and re-mark D1's MEASURED facts and its five declared-build sites "
          f"(D1 § 6.0 obligation 2 — any version change, patch bumps included); or install "
          f"{DECLARED}; or point MEZZ_HARNESS_BIN at a bundle to inspect one WITHOUT that being "
          f"evidence about {DECLARED}.")
    sys.exit(1)

if not BIN_OVERRIDE:
    notes.append(f"ground truth: Claude Code {DECLARED} (D1's declared capture build) at {BIN}")
HOOKS = harness_truth()
notes.append(f"harness hooks re-derived from the installed binary: {len(HOOKS)}")
ca, cb = value_set_controls()
notes.append(f"value-set extractor control passed (two declarations resolved to "
             f"{ca} and {cb} distinct members; a fabricated field raised)")

text = DOCTEXT
lines = text.split("\n")

# ---------- 1. fixture keys must be real keys of their hook ------------------------
# POPULATION: every payload the appendix publishes, read by `d1_appendix.py` — the ONE
# parser for § 17 in this repo, shared with `bin/harness-fixture-drift.py`.  It used to be
# spelled here as well, and two spellings of one grammar are free to disagree about what the
# appendix contains: the first thing a disagreement produces is one gate reporting clean over
# a population the other one can see.  It refuses rather than narrowing — a payload block it
# cannot parse or cannot classify raises instead of dropping out of the count.
try:
    APPENDIX = parse_appendix(text)
except AppendixError as e:
    print(f"FAILURES (1):\n  - D1 § 17 cannot be read, so no fixture can be checked: {e}")
    sys.exit(1)
fixtures = [(p.line, p.obj) for p in APPENDIX.payloads]
notes.append(f"captured-payload fixtures found: {len(fixtures)} "
             f"(D1 § {APPENDIX.number}, parsed by tools/design/d1_appendix.py)")
asserted = via_base = 0
for line, o in fixtures:
    h = o["hook_event_name"]
    if h not in HOOKS:
        fail.append(f"L{line}: fixture claims hook {h!r}, which the installed harness does not declare")
        continue
    for k in o:
        asserted += 1
        if k in HOOK_COMMON[h]:
            via_base += 1
        if k not in HOOKS[h]:
            fail.append(f"L{line}: fixture {h} carries key {k!r}, absent from the harness's own schema")
# Reported because it is the size of what the derivation carries: these are the assertions
# that used to resolve against a list typed into this file and now resolve against the
# build's own base schema.  A run where it is 0 is a run that says nothing about the base
# resolver, whatever else it reports.
notes.append(f"fixture-key assertions resolved against the DERIVED base schema: "
             f"{via_base}/{asserted}")

# ---------- 2. every hook the doc names is classified -----------------------------
subtbl = re.search(r"\| Hook \| What the reporter does with it \| Events \|\n\|[-|]+\|\n(.*?)\n\n",
                   text, re.S)
sub  = set(re.findall(r"^\| `([A-Za-z]+)` \|", subtbl.group(1), re.M)) if subtbl else set()
if not subtbl:
    fail.append("§ 6.0's hook subscription table not found — the hook population cannot be derived")
notsub_row = re.search(r"does \*\*not\*\* subscribe: (.+?) \|", text, re.S)
notsub = set(re.findall(r"`([A-Za-z]+)`", notsub_row.group(1))) if notsub_row else set()
notes.append(f"hooks subscribed: {len(sub)}; explicitly not-subscribed: {len(notsub)}")
for h in sorted(HOOKS):
    if re.search(rf"`{h}`", text) and h not in sub and h not in notsub:
        fail.append(f"hook {h!r} is referenced but appears in neither the subscription table "
                    f"nor the not-subscribed list — undeclared, not decided")

# ---------- 3. every subscribed hook that can be measured has a fixture ------------
# EVERY subscribed hook has a fixture -- a real capture or a labelled DOCS-CITED stub.
# A missing fixture is a failure, never a skip: the whole point of the guard is that it
# cannot report clean over a hook it never looked at.
fixture_hooks = {o["hook_event_name"] for _, o in fixtures}
for h in sorted(sub & set(HOOKS)):
    if h not in fixture_hooks:
        fail.append(f"subscribed hook {h!r} has NO fixture -- neither a capture nor a "
                    f"DOCS-CITED stub, so the drift guard would skip it")
# The capture/stub split is the APPENDIX's, read off the region each payload sits in — not
# re-derived here from a `text.find("### 17.1")` literal, which is a second anchor for the
# same fact and the one that goes stale the day the document is renumbered.
stub_block = APPENDIX.stub_section
stubs    = {p.hook for p in APPENDIX.stubs}
captures = [(p.line, p.obj) for p in APPENDIX.captures]
notes.append(f"  of which DOCS-CITED stubs: {len(stubs)} ({', '.join(sorted(stubs))})")
if stubs and "**not** a capture" not in stub_block:
    fail.append("stub fixtures are not labelled as stubs -- a stub read as a capture is a "
                "false MEASURED, which is this document's own defect class")

# ---------- 3b. the appendix's own reproduced-capture counts are re-derived --------
# The raw capture run is not committed, so "56 payloads" is provenance and cannot be
# checked.  What IS reproduced here can be, and the document states those two numbers.
n_cap, n_cap_hooks = len(captures), len({o["hook_event_name"] for _, o in captures})
# The run-provenance figures are the DOCUMENT's to state and this check does not know them:
# matching them as literals here would pin the tool to one capture run the same way `BIN`
# pinned it to one build, and the next re-capture would red on its own correct edit.
vol = re.search(r"\| Volume \| \*\*\d+ payloads across \d+ hook events\*\* captured; "
                r"\*\*(\d+) reproduced below\*\*.*?\*\*(\d+)\*\* hooks", text)
if not vol:
    fail.append("§ 17's Volume row is not in the form this check re-derives — the "
                "reproduced-capture counts would go unchecked")
else:
    if int(vol.group(1)) != n_cap:
        fail.append(f"§ 17 claims {vol.group(1)} reproduced captures; the appendix contains {n_cap}")
    if int(vol.group(2)) != n_cap_hooks:
        fail.append(f"§ 17 claims {vol.group(2)} distinct hooks among the reproduced captures; "
                    f"the appendix contains {n_cap_hooks}")
notes.append(f"reproduced captures re-derived from the appendix: {n_cap} across {n_cap_hooks} hooks")

# ---------- 4. every harness-fact row carries exactly one state -------------------
tbl = re.search(r"\| Fact this design rests on \| Verbatim key \| State \|\n\|[-|]+\|\n(.*?)\n\n",
                text, re.S)
if not tbl:
    fail.append("§ 6.0's harness-fact table not found — the marker population cannot be derived")
    rows = []
else:
    rows = [r for r in tbl.group(1).split("\n") if r.startswith("|")]
notes.append(f"harness-fact rows: {len(rows)}")
for r in rows:
    states = [s for s in ("MEASURED", "DOCS-CITED", "UNVERIFIED") if s in r]
    if not states:
        fail.append(f"harness-fact row carries NO state marker: {r[:110]}")
for want in ("MEASURED", "DOCS-CITED", "UNVERIFIED"):
    if not any(want in r for r in rows):
        fail.append(f"no harness-fact row is marked {want} — the three-state rule is not in use")

# ---------- 5. UNVERIFIED rows must carry a cost and a closure --------------------
for r in rows:
    if "UNVERIFIED" in r and not re.search(r"[Cc]ost if wrong|not needed|Nothing to close|"
                                           r"[Rr]ead it at|Closed by|moves with it", r):
        fail.append(f"UNVERIFIED row names no cost-if-wrong and no closure act: {r[:110]}")

# ---------- 6. HARNESS ENUM VALUE SETS: doc == binary, at every stated site --------
# This is the round-4 binding.  Population: § 6.0's enum-source table, whose own coverage
# against the doc's full enum population is checked by verify-event-schema.py -- so a new
# harness-sourced enum cannot escape both tools.
BARE = re.compile(r"^[a-z][a-z0-9_]*$")

def section_bounds(num):
    """Line range of the `### <num> ...` (or `## <num>`) heading's section."""
    start = None
    for i, l in enumerate(lines):
        m = re.match(r"^#{2,4}\s+(\d+(?:\.\d+)?)[\s.]", l)
        if not m:
            continue
        if start is None and m.group(1) == num:
            start = i
        elif start is not None:
            return start, i
    return (start, len(lines)) if start is not None else (None, None)

def value_runs(line):
    """Maximal runs of backticked bare identifiers joined only by ` \\| ` or `, `."""
    toks = [(m.start(), m.end(), m.group(1)) for m in re.finditer(r"`([^`]*)`", line)]
    runs, cur, prev_end = [], [], None
    for s, e, v in toks:
        joiner = line[prev_end:s] if prev_end is not None else None
        if cur and BARE.match(v) and joiner in (r" \| ", ", "):
            cur.append(v)
        else:
            if len(cur) >= 2:
                runs.append(cur)
            cur = [v] if BARE.match(v) else []
        prev_end = e
    if len(cur) >= 2:
        runs.append(cur)
    return runs

def table_of(idx):
    """Line range of the contiguous `|`-prefixed block containing line idx."""
    a = b = idx
    while a > 0 and lines[a - 1].startswith("|"):
        a -= 1
    while b + 1 < len(lines) and lines[b + 1].startswith("|"):
        b += 1
    return a, b

src_tbl = re.search(r"\| Harness enum set \| Binary declaration \| This document states it at \| "
                    r"Members this reporter adds \|\n\|[-|]+\|\n(.*?)\n\n", text, re.S)
if not src_tbl:
    fail.append("§ 6.0's harness enum-source table not found — no value set can be bound to "
                "the binary, which is the round-4 check reporting nothing rather than clean")
    src_rows = []
else:
    src_rows = [r for r in src_tbl.group(1).split("\n") if r.startswith("|")]
    src_lo = text[:src_tbl.start(1)].count("\n")
    src_hi = src_lo + len(src_rows)

notes.append(f"harness enum value-set bindings: {len(src_rows)}")
checked, resolved_specs = 0, []
for r in src_rows:
    cells = [c.strip() for c in r.strip().strip("|").split("|")]
    if len(cells) != 4:
        fail.append(f"enum-source row is not four cells: {r[:110]}")
        continue
    setname, binspec, locator, extras_cell = cells
    spec = binspec.strip("`")
    try:
        want = set(binary_value_set(spec))
    except ValueError as e:
        fail.append(f"enum-source row {setname}: {e}")
        continue
    resolved_specs.append((spec, frozenset(want)))
    extras = set(re.findall(r"`([^`]*)`", extras_cell))
    lm = re.match(r"§\s*(\d+(?:\.\d+)?)\s*›\s*(table\s+)?`([^`]*)`", locator)
    if not lm:
        fail.append(f"enum-source row {setname}: locator {locator!r} is not "
                    "`§ N.N › `label`` or `§ N.N › table `label``")
        continue
    sec, is_table, label = lm.group(1), bool(lm.group(2)), lm.group(3)
    lo, hi = section_bounds(sec)
    if lo is None:
        fail.append(f"enum-source row {setname}: § {sec} not found")
        continue
    hits = []
    for i in range(lo, hi):
        if src_rows and src_lo <= i <= src_hi:      # never match the binding table itself
            continue
        l = lines[i]
        if not l.startswith("|"):
            continue
        first = re.search(r"`([^`]*)`", l)
        if not first or first.group(1) != label:
            continue
        if is_table or value_runs(l):
            hits.append(i)
    if len(hits) != 1:
        fail.append(f"enum-source row {setname}: locator {locator!r} matched {len(hits)} "
                    f"document sites, expected exactly 1 — the site moved or is ambiguous")
        continue
    if is_table:
        a, b = table_of(hits[0])
        got = {v for i in range(a, b + 1) for run in value_runs(lines[i]) for v in run}
    else:
        runs = value_runs(lines[hits[0]])
        got = set(max(runs, key=len))
    expect = want | extras
    if got != expect:
        missing, extra = sorted(expect - got), sorted(got - expect)
        fail.append(
            f"L{hits[0]+1}: value-set drift for {setname} at {locator} — "
            f"the installed binary declares {len(want)} members"
            + (f"; MISSING from the document: {missing}" if missing else "")
            + (f"; stated but NOT declared by the binary: {extra}" if extra else ""))
    checked += 1
notes.append(f"harness enum value sets asserted against the binary: {checked}")

# ---------- 6b. CONTROL: module-local identifier resolution is load-bearing --------
# The resolutions above are only worth anything if resolving an identifier in the module
# that referenced it gives a DIFFERENT answer from taking the first `<name>=` in the
# bundle.  Re-resolve every spec the document named with the global-first strategy and
# require at least one to disagree: that is this extractor shown capable of the other
# answer.  Nothing here asserts a member list -- a stored list is what the tool exists
# not to have -- only that the two strategies are distinguishable and which one ran.
if resolved_specs:
    _SCOPE = "global"
    for f_ in (_ident_array, binary_value_set):
        f_.cache_clear()
    diverged = []
    for spec, local_set in resolved_specs:
        try:
            other = frozenset(binary_value_set(spec))
        except (ValueError, SystemExit):
            other = None
        if other != local_set:
            diverged.append(spec)
    _SCOPE = "local"
    for f_ in (_ident_array, binary_value_set):
        f_.cache_clear()
    if diverged:
        notes.append(f"scope control passed: module-scoped identifier resolution changes the "
                     f"answer for {len(diverged)}/{len(resolved_specs)} bound sets "
                     f"({', '.join(sorted(set(diverged)))}) — global-first-match would have "
                     f"reported a different set for those, and the local answer is what ran")
    else:
        notes.append(f"scope control INCONCLUSIVE on this build: all {len(resolved_specs)} "
                     f"bound sets resolve identically under both strategies, so nothing here "
                     f"demonstrates the resolver discriminating between modules")

# ---------- 7. round-2 finding ids must not leak ----------------------------------
for pat in [r"\bB-[1-6]\b", r"\bM-(?:[1-9]|1[0-2])\b", r"\bm-(?:[1-9]|1[0-5])\b", r"\bh-[1-4]\b"]:
    for m in re.finditer(pat, text):
        fail.append(f"L{text[:m.start()].count(chr(10))+1}: review finding id leaked: {m.group(0)}")

# ---------- report ----------------------------------------------------------------
for n in notes:
    print(n)
if fail:
    print(f"\nFAILURES ({len(fail)}):")
    for f in fail:
        print("  -", f)
    sys.exit(1)
print("HARNESS-FACT CHECKS PASS")
